version: '3'
services:
  test:
    image: bendda/mitopy:latest
    stdin_open: True
    tty: True
    command: ["pytest"]
    working_dir: /app
    volumes:
      - ./test:/app/test
  mitopy:
    image: bendda/mitopy:latest
    stdin_open: True
    tty: True
    volumes:
      - ./example_data:/example_data
      - ./data:/data
