name: Tests
on: push

permissions:
  checks: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: docker compose run test